# Estimador Máximo Verosímil

In [ ]:
from scipy.stats import bernoulli
import numpy as np 
import sympy 
from sympy.abc import x, z 

In [ ]:
fp = bernoulli(0.7)
fp.rvs(30)

array([1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 1])

In [ ]:
sum(fp.rvs(30))/30

0.7

In [ ]:
xs = fp.rvs(100)

sum(xs)/100

0.78

In [ ]:
xs

array([0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1])

In [ ]:
p = sympy.symbols("p", positive = True)

p

p

In [ ]:
np.cumsum(xs)

array([ 0,  1,  2,  3,  4,  4,  5,  6,  6,  7,  8,  9, 10, 10, 10, 11, 12,
       13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
       30, 31, 32, 33, 34, 35, 35, 35, 36, 37, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 46, 46, 47, 48, 49, 50, 51, 51, 52, 53, 54, 54, 54, 55,
       56, 57, 58, 59, 60, 61, 62, 62, 63, 64, 65, 65, 65, 65, 66, 66, 67,
       68, 69, 70, 70, 70, 71, 71, 72, 73, 74, 74, 75, 76, 77, 78])

In [ ]:
f = p**x*(1-p)**(1-x)
f

p**x*(1 - p)**(1 - x)

In [ ]:
J = np.prod([f.subs(x, i) for i in xs ] )

logJ = sympy.expand_log(sympy.log(J))

print(J)

print(logJ)

p**78*(1 - p)**22
78*log(p) + log((1 - p)**22)


In [ ]:
phat = sympy.solve(sympy.diff(logJ,p),p)[0]

phat

39/50

In [ ]:
abs(phat-0.7)<0.7*0.2 

True

In [ ]:
import pandas as pd

d = {"Horas": [5.0, 6.5, 8.0, 12.0, 14.3],
     "Calif": [50, 55, 62, 75, 85] } 

df = pd.DataFrame(d) 

df

Horas  Calif
0    5.0     50
1    6.5     55
2    8.0     62
3   12.0     75
4   14.3     85

In [ ]:
df.describe()

Horas      Calif
count   5.00000   5.000000
mean    9.16000  65.400000
std     3.87982  14.432602
min     5.00000  50.000000
25%     6.50000  55.000000
50%     8.00000  62.000000
75%    12.00000  75.000000
max    14.30000  85.000000

In [ ]:
df['Horas'].mean(), df["Horas"].var(), 

(9.16, 15.053)

In [ ]:
df["Calif"].mean(), df["Calif"].var() 

(65.4, 208.3)

In [ ]:
from scipy import stats 
from scipy.stats import bernoulli, binom

In [ ]:
rvs = bernoulli.rvs(0.7, size = 10000)

rvs.mean()

0.7026

In [ ]:


rvs2 = binom.rvs(10, 0.7, size=1000)
rvs2.mean()

6.98